# based on https://github.com/pcolby/bipolar/blob/master/.travis.yml

language: cpp

matrix:
  include:
    # QT on mac apparently doesn't support gcc
    - os: linux
      dist: xenial
      compiler: clang
      services: xvfb
    - os: linux
      dist: xenial
      compiler: gcc
      services: xvfb
    - os: osx
      osx_image: xcode9.4
      compiler: clang

before_install:
#  - '[[ "$TRAVIS_OS_NAME" != linux || -z "$PPA" ]] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'

install:
#  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || sudo apt-get -qy install qt${QT}base qt${QT}xmlpatterns libgl1-mesa-dev'
#  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install qt5-qmake qtbase5-dev'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt'

before_script:
  # download statically linked libSBML library
#  - '[ "$TRAVIS_OS_NAME" != linux ] || wget https://github.com/lkeegan/libsbml-static-linux/releases/latest/download/libsbml-static-linux.tgz'
#  - '[ "$TRAVIS_OS_NAME" != linux ] || tar xzvf libsbml-static-linux.tgz -C libsbml'
#  - '[ "$TRAVIS_OS_NAME" != osx ] || wget https://github.com/lkeegan/libsbml-static-osx/releases/latest/download/libsbml-static-osx.tgz'
#  - '[ "$TRAVIS_OS_NAME" != osx ] || tar xzvf libsbml-static-osx.tgz -C libsbml'
  - wget https://github.com/lkeegan/libsbml-static-$TRAVIS_OS_NAME/releases/latest/download/libsbml-static-$TRAVIS_OS_NAME.tgz'
  - tar xzvf libsbml-static-$TRAVIS_OS_NAME.tgz -C libsbml
  - ls libsbml
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[ "$TRAVIS_OS_NAME" != linux ] || export QT_SELECT=qt5'
  - qmake -v
  - mkdir build
  - cd build
  - qmake -Wall ../spatial-model-editor.pro

  #- qmake -o "$TRAVIS_BUILD_DIR-build" -r -Wall -Wlogic -Wparser CONFIG+=debug_and_release "$TRAVIS_BUILD_DIR"

script:
  - make
  - ls
  - '[ "$TRAVIS_OS_NAME" != osx ] || make -C "pkg/osx" dmg'

  - '[ "$TRAVIS_OS_NAME" != osx ] || otool -L spatial-model-editor'
  - '[ "$TRAVIS_OS_NAME " != linux ] || ldd spatial-model-editor'

  # Run test (TODO)
  # Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
  # - xvfb-run --server-args="-screen 0 1024x768x24" make test

notifications:
  email: false

