language: cpp

env:
  global:
    - QT5_INSTALL_PREFIX="/opt/qt5-static"

matrix:
  include:
    # linux release build: gcc 5.4.0 on ubuntu 16.04
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - libxkbcommon-dev
            - lcov
      env: 
        - DEPLOY_FILE="spatial-model-editor"
        - COVERAGE="upload"
    # osx release build: xcode 9.4.1 [9F2000], macOS 10.13
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: DEPLOY_FILE="spatial-model-editor.dmg"
    # other test builds
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          packages:
            - libxkbcommon-dev
      services: xvfb

before_script:
  # install pre-compiled Qt5 binaries & static libraries to $QT5_INSTALL_PREFIX
  # (note this has to match the install prefix hard coded in the pre-compiled library)
  - wget "https://github.com/lkeegan/qt5-static/releases/latest/download/qt5-static-$TRAVIS_OS_NAME.tgz"
  - sudo tar xzvf qt5-static-$TRAVIS_OS_NAME.tgz -C /
  # export path for Qt5 binaries
  - export PATH=$QT5_INSTALL_PREFIX/bin:$PATH
  - qmake -v
  # download pre-compiled static libSBML library
  - wget "https://github.com/lkeegan/libsbml-static/releases/latest/download/libsbml-static-$TRAVIS_OS_NAME.tgz"
  - mkdir -p libsbml
  - tar xzvf libsbml-static-$TRAVIS_OS_NAME.tgz -C libsbml
  - ls libsbml

script:
  # run qmake to generate make file
  - mkdir build
  - cd build
  - qmake -Wall -config release ../spatial-model-editor.pro
  # compile executable
  - make -j2
  # check dependencies of resulting executable
  - '[ "$TRAVIS_OS_NAME" != osx ] || otool -L spatial-model-editor.app/Contents/MacOS/spatial-model-editor'
  - '[ "$TRAVIS_OS_NAME" != linux ] || ldd spatial-model-editor'
  # for osx package app dir as a .dmg
  - '[ "$TRAVIS_OS_NAME" != osx ] || hdiutil create spatial-model-editor -fs HFS+ -srcfolder spatial-model-editor.app'
  # compile and run unit tests
  - cd ../
  - mkdir build-tests
  - cd build-tests
  - '[ "$TRAVIS_OS_NAME" != linux ] || qmake -Wall -config debug ../test.pro'
  # -config debug fails on osx because it looks for non-existent "debug" qt5 static libraries
  - '[ "$TRAVIS_OS_NAME" != osx ] || qmake -Wall -config release ../test.pro'
  - make -j2
  - '[ "$TRAVIS_OS_NAME" != linux ] || ./test -d=yes'
  - '[ "$TRAVIS_OS_NAME" != osx ] || ./test.app/Contents/MacOS/test -d=yes'
  # upload coverage report
  - '[ "$COVERAGE" != "upload" ] || lcov --directory . --capture --output-file coverage.info'
  - '[ "$COVERAGE" != "upload" ] || lcov --remove coverage.info "catch/*" "/usr/*" "*/catch/*" "*/test/*" --output-file coverage.info'
  - '[ "$COVERAGE" != "upload" ] || lcov --list coverage.info'
  - '[ "$COVERAGE" != "upload" ] || bash <(curl -s https://codecov.io/bash) -X gcov -f "coverage.info"'
  - cd ../build

notifications:
  email: false
deploy:
  # if build is tagged, upload executable to github release
  provider: releases
  api_key:
    secure: E0WtptZea2n40eN+FBYZ2XYv/pjKUjVFZavl8BTVYhidzXYuT/DvhoehPVauJRy/t5QLMtmyd5ww9dhYkIcNcpAc1INrUlYG274D8xgXwbgsftmFbMqdrKR9f/qkynP0r6LCd1p0Tuhxxf37OcTYVEOjbvV+KsTzpWHtS9AqZGvMfv/rpI4r/Zu/LfGBs2T7Rr8Mlfy5YBI2L7lGka3ziTIic01pKDfjHJQ2xD2N366mEqcpB0vjF8c9b+qIUbQ8g8ybLoMfKM6ZSvcpz2NmLQK8l8gzzTN/k1PI2DJxmzi+9G031RXLAXvbR8I8NEQlZfsicepHk0m13EI7x5/TIGaa2ngSgX1W7oAL0IAkJFpcWcN5RQOgowCBAB/UnHCX8EgnBAiD8eTlc4DUC2WY84Dr3EcdhLg0bEX/Ky4mDAxt0QgABG0hEU3kE6USsUvp7IZmnCEdu8e+F/HRmvSUqECI9FvjmpHdBHwIv6anVA2pndN/ZGn4+4BWbo6IwycAh0FPAnvvs6guxnOqQW/eMRgBI3y4grzEYP/bPzlL1W6q42r6fwvh45LtcgC+joAoJCL3I51QcZ1joMY/OShSaKi3MnokImmb/GPRvebe3hDGGSsEAarrmIRb0zCMYDMdHzA+pqeojGZf6SCfIculmeE1MO2t/DqumxQRxTGx+8k=
  file: $DEPLOY_FILE
  skip_cleanup: true
  on:
    repo: lkeegan/spatial-model-editor
    overwrite: true
    tags: true
    all_branches: true
    condition: $DEPLOY_FILE != ""
