# based on https://github.com/pcolby/bipolar/blob/master/.travis.yml

language: cpp

os:
  - linux
  - osx

dist: xenial

compiler:
  - clang
 # - gcc

env:
  # Tip: curl -s 'https://api.launchpad.net/1.0/~beineri/ppas?ws.size=200' | jq -r '"beineri/" + .entries[].name' | sed -nEe 's/.*opt-qt(([0-9]{2})[0-9]?|-([0-9])+\.([0-9]+)\.([0-9]+))-xenial/  - QT=\2\3\4 PPA=&/p'
  - QT=512 PPA=beineri/opt-qt-5.12.1-xenial

before_install:
  - '[[ "$TRAVIS_OS_NAME" != linux || -z "$PPA" ]] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install libqt5webkit5-dev qtdeclarative5-dev libxml2-dev zlib1g-dev libbz2-dev'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev'
  # Pin OSX to Qt 5.12.1 for now, since the Qt 5.12.2 Brew formula (#9980171) has an odd build issue.
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/bc03ca8ad8f74be348801c99b78905926d91abc1/Formula/qt.rb'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt'

before_script:
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  - qmake -v
  - mkdir build
  - cd build
  - qmake ../spatial-model-editor.pro

  #- qmake -o "$TRAVIS_BUILD_DIR-build" -r -Wall -Wlogic -Wparser CONFIG+=debug_and_release "$TRAVIS_BUILD_DIR"

script:
  - make
  - '[ "$TRAVIS_OS_NAME" != osx ] || make -C "pkg/osx" dmg'
  # Run test (TODO)
  # Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
  # - xvfb-run --server-args="-screen 0 1024x768x24" make test

services:
  - xvfb
notifications:
  email: false

