# based on https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_qt5_qtest/blob/master/.travis.yml
dist: xenial
sudo: required
notifications:
  email: false
language:
  - cpp
compiler:
  - gcc
before_install:
  # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
install: 
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Build test
  #- qmake -qt=qt5 travis_qmake_gcc_cpp14_qt5_qtest_test.pro
  #- make
  # Build normal
  - mkdir build
  - cd build
  - qmake -qt=qt5 ../spatial-model-editor.pro
  - make
  # Run test
  #- ./travis_qmake_gcc_cpp14_qt5_qtest_test