# based on https://github.com/pcolby/bipolar/blob/master/.travis.yml

language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      services: xvfb
    - os: linux
      dist: xenial
      compiler: gcc
      services: xvfb
    - os: osx
      osx_image: xcode10.2
      compiler: clang

before_install:
#  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'

install:
#  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install qt5-qmake qtbase5-dev'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt'

before_script:
  # download statically linked Qt5 library
  - '[ "$TRAVIS_OS_NAME" != linux ] || wget "https://github.com/lkeegan/qt5-static-linux/releases/latest/download/qt5-static-linux.tgz"'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo tar xzvf qt5-static-linux.tgz -C /'

  # download statically linked libSBML library
  - wget "https://github.com/lkeegan/libsbml-static-$TRAVIS_OS_NAME/releases/latest/download/libsbml-static-$TRAVIS_OS_NAME.tgz"
  - mkdir -p libsbml
  - tar xzvf libsbml-static-$TRAVIS_OS_NAME.tgz -C libsbml
  - ls libsbml  

  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
#  - '[ "$TRAVIS_OS_NAME" != linux ] || export QT_SELECT=qt5'
  - '[ "$TRAVIS_OS_NAME" != linux ] || export PATH=opt/qt-5.12.3/bin:$PATH'
  - qmake -v
  - '[ "$TRAVIS_OS_NAME" != osx ] || xcrun -sdk macosx --show-sdk-path'
  - mkdir build
  - cd build
  - qmake -Wall -config release ../spatial-model-editor.pro

  #- qmake -o "$TRAVIS_BUILD_DIR-build" -r -Wall -Wlogic -Wparser CONFIG+=debug_and_release "$TRAVIS_BUILD_DIR"

script:
  - make
  - ls
  - '[ "$TRAVIS_OS_NAME" != osx ] || otool -L spatial-model-editor.app/Contents/MacOS/spatial-model-editor'
  - '[ "$TRAVIS_OS_NAME" != osx ] || macdeployqt spatial-model-editor.app -dmg'
  - ls

  - '[ "$TRAVIS_OS_NAME" != linux ] || ldd spatial-model-editor'

  # Run test (TODO)
  # Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
  # - xvfb-run --server-args="-screen 0 1024x768x24" make test

notifications:
  email: false

