# windows release build: MinGW-w64 6.3.0 i686 on Windows Server 2012 R2
image:
  - Visual Studio 2015
install:
  - set PATH=%PATH%;C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin

before_build:
  # install pre-compiled Qt5 binaries & static libraries
  - mkdir qt5
  - cd qt5
  - appveyor DownloadFile "https://github.com/lkeegan/qt5-static/releases/latest/download/qt5-static-win32.zip"
  - 7z x qt5-static-win32.zip
  - dir install
  - cd ..
  # export path for Qt5 binaries
  - set PATH=%APPVEYOR_BUILD_FOLDER%/qt5/install/bin;$PATH
  - qmake -v
  # download pre-compiled static libSBML library
  - appveyor DownloadFile "https://github.com/lkeegan/libsbml-static/releases/latest/download/libsbml-static-win32.tgz"
  - mkdir libsbml
  - cd libsbml
  - 7x x libsbml-static-win32.zip
  - dir
  - cd ..

build_script:
  # run qmake to generate make file
  - mkdir build
  - cd build
  - qmake -Wall -config release ../spatial-model-editor.pro
  # compile executable
  - mingw32-make -j2
  # check dependencies of resulting executable
  #
  - dir

after_build:
  - 7z a %APPVEYOR_BUILD_FOLDER%\qt5-static-win32.zip %QT5_INSTALL_PREFIX%

artifacts:
  - path: build/spatial-model-editor.exe
    name: spatial-model-editor

deploy:
  provider: GitHub
  description: 'win32 release'
  artifact: spatial-model-editor
  auth_token:
    secure: AzIgTar/Vk7S6hA8HAZAImacEIrbwmfrR6PJ+qHuAQHuLyPSAAcpI5rl/w6BumKp
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
