image:
  - Visual Studio 2015
install:
  - set QTDIR=C:\Qt\5.12.2\mingw73_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - appveyor DownloadFile https://sourceforge.net/projects/sbml/files/libsbml/5.18.0/experimental/binaries/Windows/libSBML-5.18.0-win64.zip
  - 7z x libSBML-5.18.0-win64.zip
  - dir
  - move libSBML-5.18.0-win64\bin\libsbml-static.lib libsbml-static.lib
  - qmake spatial-model-editor.pro
  - mingw32-make