jobs:
- job: 'ubuntu1604'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - checkout: self
  - script: |
      sudo apt update
      sudo apt install -y libxkbcommon-dev
  - script: |
      g++ --version
- job: 'osx1014'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - checkout: self
  - script: |
      clang++ --version
